---
title: ""
output:
  html_document:
    theme: sandstone
    highlight: pygments
    fig_width: 7
    css: styles.css
    include:
      before_body: header.html
      after_body: footer.html
---

<p>&nbsp;</p>

### Data science • Investment thoughts • Geeky stuff

<p class="half-line">&nbsp;</p>

This site is a window into my interests and work, which often coincide. Most of my remaining time is spent fruitfully with my wife and boy, with friends or with charities … or wasted by supporting sports teams that rarely win.

At work, I use data science to improve how asset owners select asset managers. I also chair the Investment Committee of the Society of Pension Professionals. Before that, I penned research papers on a wide range of investment subjects.

<p>&nbsp;</p>

#### Latest posts

<p class="half-line">&nbsp;</p>
  
  * Building a [dynamic dashboard of Brexit referendum data](BrexitDashboard.html)

  * [Mapping Brexit referendum data](packageForThat.html)  for an R training course that I delivered

  * Final-week [projections for my football competition](2016PremPredict3.html) 
  
  * [Where in the order have the best batsmen batted?](Batting.html)
  
  * Where is the [best place to commute to Reigate?](Commute.html)
  
  * Fixing [asset manager evaluation](Performance.html)

<p>&nbsp;</p>

#### Latest tweets

<p class="half-line">&nbsp;</p>

<a class="twitter-timeline" data-dnt="true" href="https://twitter.com/InvestmentRP"
data-chrome="noheader noborders transparent nofooter"
height="800"
data-widget-id="308290928899137536">Tweets by @InvestmentRP</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<br></br>

---

